<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="NoStatesNoTriggers.xml" />
    <None Remove="StateManager\ArbitraryNamespace.xml" />
    <None Remove="StateManager\IncorrectStateBaseClass.xml" />
    <None Remove="StateManager\IncorrectTypeName.xml" />
    <None Remove="StateManager\MasterStateXmlFileWithSubStateXmlFileRefs.xml" />
    <None Remove="TestStateFile.xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="StateManager\MasterStateXmlFileWithSubStateXmlFileRefs.xml" />
    <EmbeddedResource Include="StateManager\TestStateFile.xml" />
    <EmbeddedResource Include="StateManager\ArbitraryNamespace.xml" />
    <EmbeddedResource Include="StateManager\DifferentNamespaces.xml" />
    <EmbeddedResource Include="StateManager\IncorrectStateBaseClass.xml" />
    <EmbeddedResource Include="StateManager\IncorrectTypeName.xml" />
    <EmbeddedResource Include="StateManager\BasicTransitions.xml" />
    <EmbeddedResource Include="StateManager\WithTriggersTagAndOneStateStateFile.xml" />
    <EmbeddedResource Include="StateManager\WithTriggersTagAndTwoStatesStateFile.xml" />    
    <EmbeddedResource Include="StateManager\WithTriggersStateFile.xml" />
    <EmbeddedResource Include="StateManager\InitialStateSpecified.xml" />
    <EmbeddedResource Include="StateManager\NoInitialStateSpecified.xml" />

  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Avak.StateMachine.Core\Avak.StateMachine.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="StateManager\NoStatesNoTriggers.xml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <None Update="StateManager\NoEmbeddedJustCopiedResource.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
