<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="StateManager\XmlFilesWithSubStates\MasterStateXmlFileDuplicateSubStateXmlFile.xml" />
    <EmbeddedResource Include="StateManager\XmlFilesWithSubStates\MasterStateXmlFileNoSubStateXmlFileValue.xml" />
    <EmbeddedResource Include="StateManager\XmlFilesWithSubStates\MasterStateXmlFileNoSubStateAssembly.xml" />
    <EmbeddedResource Include="StateManager\XmlFilesWithSubStates\MasterStateXmlFileNoSubStateAssemblyValue.xml" />
    <EmbeddedResource Include="StateManager\XmlFilesWithSubStates\MasterStateXmlFileNoSubStateXmlFile.xml" />
    <EmbeddedResource Include="StateManager\XmlFilesWithSubStates\MasterStateXmlFileTwoXmlFilesInSameAssembly.xml" />
    <EmbeddedResource Include="StateManager\XmlFilesWithSubStates\MasterStateXmlFileWithSubStateXmlFileRefs.xml" />
    <EmbeddedResource Include="StateManager\NameSpaceTestsXmlFiles\ArbitraryNamespace.xml" />
    <EmbeddedResource Include="StateManager\NameSpaceTestsXmlFiles\DifferentNamespaces.xml" />
    <EmbeddedResource Include="StateManager\NameSpaceTestsXmlFiles\EmptyStringDefaultNamespace.xml" />
    <EmbeddedResource Include="StateManager\NameSpaceTestsXmlFiles\NoNamespaceAttribute.xml" />
    <EmbeddedResource Include="StateManager\TestStateFile.xml" />
    <EmbeddedResource Include="StateManager\IncorrectStateBaseClass.xml" />
    <EmbeddedResource Include="StateManager\IncorrectTypeName.xml" />
    <EmbeddedResource Include="StateManager\BasicTransitions.xml" />
    <EmbeddedResource Include="StateManager\WithTriggersTagAndOneStateStateFile.xml" />
    <EmbeddedResource Include="StateManager\WithTriggersTagAndTwoStatesStateFile.xml" />
    <EmbeddedResource Include="StateManager\InitialStateSpecified.xml" />
    <EmbeddedResource Include="StateManager\NoInitialStateSpecified.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Avak.StateMachine.Core\Avak.StateMachine.Core.csproj" />
    <ProjectReference Include="..\SSMFrUntTs\UT11\Avak.StateMachine.Core.Tests.SSM_UT11_L2_1\Avak.StateMachine.Core.Tests.SSM_UT11_L2_1.csproj" />
    <ProjectReference Include="..\SSMFrUntTs\UT12\Avak.StateMachine.Core.Tests.SSM_UT12_L2_1\Avak.StateMachine.Core.Tests.SSM_UT12_L2_1.csproj" />
    <ProjectReference Include="..\SSMFrUntTs\UT12\Avak.StateMachine.Core.Tests.SSM_UT12_L2_2\Avak.StateMachine.Core.Tests.SSM_UT12_L2_2.csproj" />
    <ProjectReference Include="..\SSMFrUntTs\UT12\Avak.StateMachine.Core.Tests.SSM_UT12_L3_1_1\Avak.StateMachine.Core.Tests.SSM_UT12_L3_1_1.csproj" />
    <ProjectReference Include="..\SSMFrUntTs\UT20\Avak.StateMachine.Core.Tests.SSM_UT20_L2_1\Avak.StateMachine.Core.Tests.SSM_UT20_L2_1.csproj" />
    <ProjectReference Include="..\SSMFrUntTs\UT20\Avak.StateMachine.Core.Tests.SSM_UT20_L2_2\Avak.StateMachine.Core.Tests.SSM_UT20_L2_2.csproj" />
    <ProjectReference Include="..\SSMFrUntTs\UT20\Avak.StateMachine.Core.Tests.SSM_UT20_L2_3\Avak.StateMachine.Core.Tests.SSM_UT20_L2_3.csproj" />
    <ProjectReference Include="..\SSMFrUntTs\UT20\Avak.StateMachine.Core.Tests.SSM_UT20_L3_1_1\Avak.StateMachine.Core.Tests.SSM_UT20_L3_1_1.csproj" />
    <ProjectReference Include="..\SSMFrUntTs\UT20\Avak.StateMachine.Core.Tests.SSM_UT20_L3_2_1\Avak.StateMachine.Core.Tests.SSM_UT20_L3_2_1.csproj" />
    <ProjectReference Include="..\SSMFrUntTs\UT20\Avak.StateMachine.Core.Tests.SSM_UT20_L3_2_2\Avak.StateMachine.Core.Tests.SSM_UT20_L3_2_2.csproj" />
    <ProjectReference Include="..\SSMFrUntTs\UT20\Avak.StateMachine.Core.Tests.SSM_UT20_L3_3_1\Avak.StateMachine.Core.Tests.SSM_UT20_L3_3_1.csproj" />
    <ProjectReference Include="..\SSMFrUntTs\UT20\Avak.StateMachine.Core.Tests.SSM_UT20_L3_3_2\Avak.StateMachine.Core.Tests.SSM_UT20_L3_3_2.csproj" />
    <ProjectReference Include="..\SSMFrUntTs\UT20\Avak.StateMachine.Core.Tests.SSM_UT20_L3_3_3\Avak.StateMachine.Core.Tests.SSM_UT20_L3_3_3.csproj" />
    <ProjectReference Include="..\SSMFrUntTs\UT20\Avak.StateMachine.Core.Tests.SSM_UT20_L4_1_1_1\Avak.StateMachine.Core.Tests.SSM_UT20_L4_1_1_1.csproj" />
    <ProjectReference Include="..\SSMFrUntTs\UT20\Avak.StateMachine.Core.Tests.SSM_UT20_L4_2_1_1\Avak.StateMachine.Core.Tests.SSM_UT20_L4_2_1_1.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <None Update="StateManager\NoEmbeddedJustCopiedResource.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
